-- ==============================================================================
-- Database Migration: Treatment Payments & Balance Management
-- ==============================================================================

-- 1. Ensure the 'balance' column exists on 'treatments' table
ALTER TABLE treatments 
ADD COLUMN IF NOT EXISTS balance NUMERIC(10, 2);

-- 2. Create the 'treatment_payments' table
CREATE TABLE IF NOT EXISTS treatment_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id BIGINT NOT NULL REFERENCES treatments(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Create indexes for high-performance querying
CREATE INDEX IF NOT EXISTS idx_treatment_payments_treatment_id 
ON treatment_payments(treatment_id);

CREATE INDEX IF NOT EXISTS idx_treatment_payments_is_active 
ON treatment_payments(is_active);

CREATE INDEX IF NOT EXISTS idx_treatment_payments_date 
ON treatment_payments(payment_date DESC);

-- 4. Initialize 'balance' for any existing treatments without a balance set
UPDATE treatments t
SET balance = COALESCE(t.cost, 0) - COALESCE((
    SELECT SUM(p.amount)
    FROM treatment_payments p
    WHERE p.treatment_id = t.id AND p.is_active = TRUE
), 0)
WHERE t.balance IS NULL;

-- 5. Enable Row Level Security (RLS) and grant standard policies if needed
ALTER TABLE treatment_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all operations for anon on treatment_payments" 
ON treatment_payments 
FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);
